---
# Malati - Remote site (parents' home)
# Usage: ansible-playbook playbooks/site.yml -i inventories/malati/hosts.yml

all:
  children:
    # Stack groups
    homeassistant_stack:
      hosts:
        malati-pi:
          ansible_host: malati-pi  # Tailscale MagicDNS
          # For local access: ansible_host: malati-pi.local
