---
galaxy_info:
  author: mrugesh
  description: Portainer CE container management
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies: []
