$ANSIBLE_VAULT;1.1;AES256
66346639303333633265363533626434303238333232636563636131353938633238633030363638
6432663336363734303961386463656535333336653635660a396134643063656435356265313431
63633331346131373734616330343133376536363235383034343834303961356136333837386530
6637343231393265330a373330363330356666306131376336316135633064666231616537303630
34633439643639363834656363353561363661376265366339366531636332323864333930616639
61643238623436366639343733393936333135663339613136313739643266363139316564356137
66653463376263666639356131633631373965636137393565396466653730613662393662663935
30326565613935656661363138323462616234353161396362313838633434666337396566323262
63643165323635353033633665633035626261666434653133613034666162346233303064396638
61666331393034333965363737306464666662313637306338363466323861366661386163633038
65356432643736333731396231313738303663623463613332663030633038613161386438633535
61366638363535653364653165303438303335346262663163386565313839623637643061643563
64663133353732366262393762363361383865393032313638386335653736333137363365353131
32663336633464373139633536306666393433383336306237616535316531356630393861386161
65613761653732323566623833633835353965383432323061336339373135376234643166393130
37333239643733303461343364306466623065623064356136373338646433373365316361633065
61616339383533303435393365313538616232396664666663303332663766336338386633376238
63393665353436613230623837643564613234623366383362383366643136646630346334303962
31393862363539356237613038666636653038646432333861633736363361383664633861326237
39663739663937343762666535623131363563626138326665323731396534386232616133613635
62366165363061343535356666653239636237343533313230316130633639373935
